<rules>
	<rule	Name="DontDestroyStackTrace" 
		Type="Gendarme.Rules.Exceptions.DontDestroyStackTrace, Gendarme.Rules.Exceptions, Version=@GENDARME_VERSION@, Culture=neutral, PublicKeyToken=null"
		Uri="http://www.mono-project.com/Gendarme.Rules.Exceptions#DontDestroyStackTraceRule" >
		<problem>A catch block in method or property '{0}' throws the caught exception.</problem>
		<solution>If you need to throw the exception caught by the catch block, use 'throw;' instead of 'throw ex;'</solution>
	</rule>
	<rule	Name="DontSwallowErrorsCatchingNonspecificExceptionsRule"
		Type="Gendarme.Rules.Exceptions.DontSwallowErrorsCatchingNonspecificExceptionsRule, Gendarme.Rules.Exceptions, Version=@GENDARME_VERSION@, Culture=neutral, PublicKeyToken=null"
		Uri="http://www.mono-project.com/Gendarme.Rules.Exceptions#DontSwallowErrorsCatchingNonspecificExceptionsRule">
		<problem>The method '{0}' catch a nonspecific exception.</problem>
		<solution>You can rethrow the original exception for don't destroy the stacktrace, or you can handle the specific exceptions.</solution>
	</rule>
</rules>
